export const GET_REGISTRATION_REQUEST: 'GET_REGISTRATION_REQUEST' = 'GET_REGISTRATION_REQUEST';
export const GET_REGISTRATION_SUCCESS: 'GET_REGISTRATION_SUCCESS' = 'GET_REGISTRATION_SUCCESS';
export const GET_REGISTRATION_FAILED: 'GET_REGISTRATION_FAILED' = 'GET_REGISTRATION_FAILED';

export const GET_LOGIN_REQUEST: 'GET_LOGIN_REQUEST' = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS' = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILED: 'GET_LOGIN_FAILED' = 'GET_LOGIN_FAILED';

export const GET_LOGIN_OUT_SUCCESS: 'GET_LOGIN_OUT_SUCCESS' = 'GET_LOGIN_OUT_SUCCESS';

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE' = 'CREATE_ORDER_FAILURE';
export const CLEAN_ORDER_ID: 'CLEAN_ORDER_ID' = 'CLEAN_ORDER_ID';


export const SHOW_INGREDIENT_DETAILS: 'SHOW_INGREDIENT_DETAILS' = 'SHOW_INGREDIENT_DETAILS';
export const HIDE_INGREDIENT_DETAILS: 'HIDE_INGREDIENT_DETAILS' = 'HIDE_INGREDIENT_DETAILS';
export const REOPEN_INGREDIENT_DETAILS: 'REOPEN_INGREDIENT_DETAILS' = 'REOPEN_INGREDIENT_DETAILS';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const CONSTRUCTOR_REORDER: 'CONSTRUCTOR_REORDER' = 'CONSTRUCTOR_REORDER';
export const CLEAN_CONSTRUCTOR: 'CLEAN_CONSTRUCTOR' = 'CLEAN_CONSTRUCTOR';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_CONNECTION_REQUEST: 'WS_CONNECTION_REQUEST' = 'WS_CONNECTION_REQUEST';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';

export const SHOW_ORDER_DETAILS: 'SHOW_ORDER_DETAILS' = 'SHOW_ORDER_DETAILS';
export const HIDE_ORDER_DETAILS: 'HIDE_ORDER_DETAILS' = 'HIDE_ORDER_DETAILS';
export const REOPEN_ORDER_DETAILS: 'REOPEN_ORDER_DETAILS' = 'REOPEN_ORDER_DETAILS';
